# Site
repository: 99winnmin/99winnmin.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유승민
title: 서버 백엔드 엔지니어
email: ojysep9987@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  99winnmin
# facebook_username: jekyll
# linkedin_username: jameswgrant
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
